Add bookings
Dimets/java-shareit pull request #2
Opened 2022-09-09 14:55 UTC by Dimets

2022-09-10 04:01 UTC, eugene-lenkevich requested changes
Привет, Дмитрий, спасибо за PR

Внимательно посмотрел твою работу, в целом все понравилось :)
Есть совсем небольшие замечания, посмотри комментарии ниже, пожалуйста

2022-09-10 04:01 UTC, eugene-lenkevich commented on src/main/resources/schema.sql
> +    id bigint NOT NULL,
Сделал бы и тут GENERATED BY DEFAULT AS IDENTITY :)

2022-09-10 04:02 UTC, eugene-lenkevich requested changes

2022-09-10 04:02 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public List<BookingExtDto> findAllByBooker(Long userId, String state)
Если есть желание можешь попробовать применить паттерн "стратегия"

Возможно, именно для этого случая стратегия покажется избыточной (обработчики все в одну строчку), но попробовать самое то, к тому же в реальной жизни часто используется, так как часто в обработчике бывает нетривиальная логика и куча своих зависимостей :) 

Смысл такой. У тебя есть соответствие между состоянием и обработчиком этого состояния.
Можно сделать мапу
Map<String, BookingStateFetchStrategy>, где BookingStateFetchStrategy - который будут реализовывать обработчики состояния

или же, более простой вариант, в мапу засунуть методы сервиса, примерно так будет
Map<String, Supplier> handlers = ...
handlers.put("ALL", this::handleAllState) 

То есть, мы заменяем switch на поиск нужного обработчика через map :)

https://ravthiru.medium.com/strategy-design-pattern-with-in-spring-boot-application-2ff5a7486cd8

2022-09-11 21:17 UTC, Dimets commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public List<BookingExtDto> findAllByOwner(Long userId, String state)
+

2022-09-12 07:29 UTC, Dimets commented on pom.xml
> +			<version>2.7.3</version>
+

2022-09-12 07:57 UTC, Dimets commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    List<Booking> findAllByBooker_Id(Long bookerId);
+

2022-09-12 08:05 UTC, Dimets commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +public class Booking {
+

2022-09-12 08:08 UTC, Dimets commented on src/main/resources/schema.sql
> +    id bigint NOT NULL,
+

2022-09-12 08:19 UTC, Dimets commented on src/main/java/ru/practicum/shareit/item/CommentMapper.java
> +    public static CommentDto toCommentDto(Comment comment) {
Тут наверное не совсем понял, пометил методы в мапперах @Bean, но вот что с этим дальше делать и в чем польза не догадался)

2022-09-12 08:20 UTC, Dimets commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public List<BookingExtDto> findAllByBooker(Long userId, String state)
попробую на досуге

2022-09-12 08:50 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/item/CommentMapper.java
> +    public static CommentDto toCommentDto(Comment comment) {
Да не :)

@Component
public class CommentMapper {
    public  CommentDto toCommentDto(Comment comment) { 
    ...
}


@Bean - это немного не то, аннотация нам потребуется если мы хотим сделать порождающий метод для данного бина в конфигурации

2022-09-12 11:18 UTC, Dimets commented on src/main/java/ru/practicum/shareit/item/CommentMapper.java
> +    public static CommentDto toCommentDto(Comment comment) {
+

2022-09-12 11:22 UTC, eugene-lenkevich approved these changes
Все супер, спасибо!

2022-09-12 11:48 UTC, merged