Add item requests
Dimets/java-shareit pull request #3
Opened 2022-09-30 13:34 UTC by Dimets

2022-10-03 17:51 UTC, eugene-lenkevich requested changes
Привет, Дмитрий, спасибо за PR

Меня впечатлили тесты, их много, это круто :)
Единственное, давай немножко поработаем с производительностью. В реальном приложении обычно тормозит что то из двух вариантов: сеть или база данных. Сеть нас пока особо не интересует, а вот базу данных можно и подкрутить, я оставил несколько коментариев, посмотри, пожалуйста

2022-10-03 17:51 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                              @RequestParam(defaultValue = "0x7fffffff") @Min(1) Integer size)
По умолчанию будет выгребаться вся таблица, вряд ли там будет больше записей, не уверен что стоит так делать, ОЗУ ж кончится, может хватит и 10и записей? :)

2022-10-03 17:51 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (bookingService.findAllByBooker(userId, BookingStatus.CURRENT.toString(),
`bookingService.findAllByBooker(userId, BookingStatus.CURRENT.toString(), 0, Integer.MAX_VALUE).size()
`
Ммм, то есть тут вытаскиваются все записи из таблицы для того чтобы унать их количество? ОЗУ кончится, записей может быть и несколько миллиардов :)

Можно сделать в репозитории метод, который будет делать select count(id) from ....

https://stackoverflow.com/questions/10696490/does-spring-data-jpa-have-any-way-to-count-entites-using-method-name-resolving

2022-10-03 17:51 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/requests/ItemRequestServiceImpl.java
> +                itemRequestDto.setItems(itemMapper.toItemDto(itemRepository.findAllByItemRequest(
В цикле выполняется несколько(много) раз завпрос
itemRepository.findAllByItemRequest(...)

Чем меньше у нас запросов тем лучше для производительности. Каждый запрос запрашивает коннект к базе данных, строит план запроса и тд и тп, в общем это достаточно дорогая операция. Получится ли переделать это на один запрос, сделать метод который будет принимать коллекцию объектов? :)

.findAllByItemRequest(Collection<ItemRequest>)

2022-10-03 18:26 UTC, Dimets commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                              @RequestParam(defaultValue = "0x7fffffff") @Min(1) Integer size)
+

2022-10-03 18:45 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (bookingService.findAllByBooker(userId, BookingStatus.CURRENT.toString(),
В принципе можно и так

А можно и попробовать что то вроде такого

existsByUserIdAndByStatus

https://www.baeldung.com/spring-data-exists-query

2022-10-03 19:36 UTC, Dimets commented on src/main/java/ru/practicum/shareit/requests/ItemRequestServiceImpl.java
> +                itemRequestDto.setItems(itemMapper.toItemDto(itemRepository.findAllByItemRequest(
но тут в цикле мне для каждого элемента нужно положить список itemRequestDto.setItems(...) Или тут мысль вытащить все одним запросом по списку ItemRequest и затем по этому списку итерироваться и делать itemRequestDto.setItems?

2022-10-04 05:14 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/requests/ItemRequestServiceImpl.java
> +                itemRequestDto.setItems(itemMapper.toItemDto(itemRepository.findAllByItemRequest(
Ну да, все верно :)

2022-10-04 05:35 UTC, Dimets commented on src/main/java/ru/practicum/shareit/requests/ItemRequestServiceImpl.java
> +                itemRequestDto.setItems(itemMapper.toItemDto(itemRepository.findAllByItemRequest(
была мысль сделать еще вот так:
`public interface ItemRequestRepositoryCustom extends JpaRepository<ItemRequest, Long> {
    @Query(nativeQuery = true)
    List<ItemRequestDto> findAllByUserNot(User userId);
}
`
Но закопался с ConverterNotFoundException пока что

Или это неверный путь в принципе?

2022-10-04 05:47 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/requests/ItemRequestServiceImpl.java
> +                itemRequestDto.setItems(itemMapper.toItemDto(itemRepository.findAllByItemRequest(
Вытащить все запросы кроме запроса конкретного пользователя? Не совсем понимаю зачем, опять таки, лучше тащить конкретные данные, есть же данные
А ошибка упала, предположу, потому что надо убрать @Query(nativeQuery = true), в этой аннотацмм в данном случае толку нет :)

2022-10-04 06:23 UTC, Dimets commented on src/main/java/ru/practicum/shareit/requests/ItemRequestServiceImpl.java
> +                itemRequestDto.setItems(itemMapper.toItemDto(itemRepository.findAllByItemRequest(
Так там и суть метода получить все  запросы других пользователей
![image](https://user-images.githubusercontent.com/34891627/193748795-ced749df-0afe-4c7f-8a79-2f258e558dff.png)

PS без  @query(nativeQuery = true) так же подает(

2022-10-04 06:53 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/requests/ItemRequestServiceImpl.java
> +                itemRequestDto.setItems(itemMapper.toItemDto(itemRepository.findAllByItemRequest(
А, ну да, тогда все верно. Аннотации не надо.

Метод ты верно назвал, надо смотреть что за ошибка, на чем именно падает, по стектрейсу
https://stackoverflow.com/questions/51200708/not-equals-condition-when-using-spring-crudrepository

2022-10-04 12:12 UTC, Dimets commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (bookingService.findAllByBooker(userId, BookingStatus.CURRENT.toString(),
.

2022-10-04 12:12 UTC, Dimets commented on src/main/java/ru/practicum/shareit/requests/ItemRequestServiceImpl.java
> +                itemRequestDto.setItems(itemMapper.toItemDto(itemRepository.findAllByItemRequest(
.

2022-10-04 13:26 UTC, eugene-lenkevich approved these changes
Ага, отлично, спасибо :)

2022-10-10 20:11 UTC, merged